### ISSUE TITLE
Server startup handling

### ISSUE THREAD

**Issue by awaisabir** [ShaneMatthias/Emaily_ReactExample#1]
https://github.com/ShaneMatthias/Emaily_ReactExample/blob/b0e6842d0ad4f851710bc0d93fe589e52360eb65/server/index.js#L14

Might want to handle any errors that pop up during server startup like:

```
app.listen(PORT, (err) => {
  if (err) { throw err; }
});
```

**Comment by awaisabir** [comment]
Please needs immediate attention

**Comment by ShaneMatthias** [comment]
I see, ill go..........



.....to a bridge and....




....weather outside
